- repo: https://github.com/mvdan/gofmt
  rev: v1.0.0
  hooks:
    - id: gofmt
      args: ["-s"]

- repo: https://github.com/golangci/golangci-lint
  rev: v1.44.0
  hooks:
    - id: golangci-lint
      args:
        [
          "run",
          "--disable-all",
          "--enable=golint",
          "--enable=gocritic",
          "--enable=goerr113",
          "--enable=gocyclo",
        ]

- repo: https://github.com/golang/tools
  rev: go1.18.1
  hooks:
    - id: goimports
      args: ["-local=yourdomain.com"]

- repo: https://github.com/dominikh/go-tools
  rev: v0.1.0
  hooks:
    - id: gocyclo
      args: ["-over=15"]

- repo: https://github.com/golang/vet
  rev: master
  hooks:
    - id: govet
      args: ["-all"]

- repo: https://github.com/go-critic/go-critic
  rev: master
  hooks:
    - id: go-critic
      args: ["--enable-all"]
