package seeder

import (
	"log"

	"github.com/AhmadAboElzahab/bridge/internal/constants"
	"github.com/AhmadAboElzahab/bridge/internal/initializers"
	"github.com/AhmadAboElzahab/bridge/internal/models"
)

func SeedMaidFormFields() {
	fields := []models.FormField{
		{
			Label:          "Email",
			FieldKey:       "email",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeEmailField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      1,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     1,
		},
		{
			Label:          "Phone Number",
			FieldKey:       "phone_number",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypePhoneField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      2,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     2,
		},
		{
			Label:          "Whatsapp Number",
			FieldKey:       "whatsapp_number",
			ModelName:      constants.MAID,
			HelpText:       "Must start with +971",
			FormFieldType:  constants.TypePhoneField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      3,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     3,
		},
		{
			Label:          "First Name",
			FieldKey:       "first_name",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeStringField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      4,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     4,
		},
		{
			Label:          "Last Name",
			FieldKey:       "last_name",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeStringField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      5,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     5,
		},
		{
			Label:          "Gender",
			FieldKey:       "gender",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      6,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     6,
			Options:        constants.GenderOptions,
		},
		{
			Label:          "Date of Birth",
			FieldKey:       "date_of_birth",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeDateField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      7,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     7,
		},
		{
			Label:          "Nationality",
			FieldKey:       "nationality",
			ModelName:      constants.MAID,
			HelpText:       "Select a country",
			FormFieldType:  constants.TypeSingleRelation,
			DataSource:     "Country:ID:Name",
			FormWidth:      2,
			FormOrder:      8,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     8,
		},
		{
			Label:          "Current Location",
			FieldKey:       "current_location",
			ModelName:      constants.MAID,
			HelpText:       "Select a country",
			FormFieldType:  constants.TypeSingleRelation,
			DataSource:     "Country:ID:Name",
			FormWidth:      2,
			FormOrder:      9,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     9,
		},
		{
			Label:          "Profile Picture",
			FieldKey:       "profile_picture",
			ModelName:      constants.MAID,
			HelpText:       "Upload a profile picture",
			FormFieldType:  constants.TypeImageField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      10,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     10,
		},
		{
			Label:          "Years of Experience",
			FieldKey:       "years_of_experience",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeIntegerField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      11,
			FormStage:      "experience",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     11,
		},
		{
			Label:          "Skills",
			FieldKey:       "skills",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeMultiRelation,
			DataSource:     "Skill:ID:Name",
			FormWidth:      2,
			FormOrder:      12,
			FormStage:      "experience",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     12,
		},
		{
			Label:          "Languages",
			FieldKey:       "languages",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeMultiRelation,
			DataSource:     "Language:ID:Name",
			FormWidth:      2,
			FormOrder:      13,
			FormStage:      "experience",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     13,
		},
		{
			Label:          "Work Preferences",
			FieldKey:       "work_preferences",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeMultiSelect,
			DataSource:     "",
			Options:        constants.WorkPreferencesOptions,
			FormWidth:      2,
			FormOrder:      14,
			FormStage:      "experience",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     14,
		},
		{
			Label:          "Bio",
			FieldKey:       "bio",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeRichField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      15,
			FormStage:      "experience",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     15,
		},
		{
			Label:          "Expected Salary",
			FieldKey:       "expected_salary",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeIntegerField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      16,
			FormStage:      "salary",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     16,
		},
		{
			Label:          "Availability",
			FieldKey:       "availability",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.AvailabilityOptions,
			FormWidth:      2,
			FormOrder:      17,
			FormStage:      "availability",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     17,
		},
		{
			Label:          "Preferred Work Location",
			FieldKey:       "preferred_work_location",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.CitiesOptions,
			FormWidth:      2,
			FormOrder:      18,
			FormStage:      "availability",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     18,
		},
		{
			Label:          "Video Introduction",
			FieldKey:       "video_introduction",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeStringField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      19,
			FormStage:      "info",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     19,
		},
		{
			Label:          "Visa Status",
			FieldKey:       "visa_status",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.VisaStatusOptions,
			FormWidth:      2,
			FormOrder:      20,
			FormStage:      "legal",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     20,
		},
		{
			Label:          "Subscription Status",
			FieldKey:       "subscription_status",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.SubscriptionStatusOptions,
			FormWidth:      2,
			FormOrder:      21,
			FormStage:      "subscription",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     21,
		},
		{
			Label:          "Subscription Plan",
			FieldKey:       "subscription_plan",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.SubscriptionPlanOptions,
			FormWidth:      2,
			FormOrder:      22,
			FormStage:      "subscription",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     22,
		},
		{
			Label:          "Subscription Start Date",
			FieldKey:       "subscription_start_date",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeDateField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      23,
			FormStage:      "subscription",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     23,
		},
		{
			Label:          "Subscription End Date",
			FieldKey:       "subscription_end_date",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeDateField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      24,
			FormStage:      "subscription",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     24,
		},
		{
			Label:          "Auto Renew",
			FieldKey:       "auto_renew",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeBoolField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      25,
			FormStage:      "subscription",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     25,
		},
		{
			Label:          "Is Profile Visible",
			FieldKey:       "is_profile_visible",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeBoolField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      26,
			FormStage:      "visibility",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     26,
		},
		{
			Label:          "First Aid Certificate",
			FieldKey:       "first_aid_certificate",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeBoolField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      27,
			FormStage:      "certificates",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     27,
		},
		{
			Label:          "Care Giver Certificate",
			FieldKey:       "care_giver_certificate",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeBoolField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      28,
			FormStage:      "certificates",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     28,
		},
		{
			Label:          "Teaching Certificate",
			FieldKey:       "teaching_certificate",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeBoolField,
			DataSource:     "",
			FormWidth:      2,
			FormOrder:      29,
			FormStage:      "certificates",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     29,
		},
		{
			Label:          "Status",
			FieldKey:       "status",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.StatusOptions,
			FormWidth:      2,
			FormOrder:      30,
			FormStage:      "status",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     30,
		},
		{
			Label:          "Religion",
			FieldKey:       "religion",
			ModelName:      constants.MAID,
			HelpText:       "",
			FormFieldType:  constants.TypeSingleSelect,
			DataSource:     "",
			Options:        constants.ReligionOptions,
			FormWidth:      2,
			FormOrder:      31,
			FormStage:      "profile",
			FormIsRequired: false,
			TableIsPinned:  false,
			TableIsVisible: true,
			TableOrder:     31,
		},
	}

	for _, field := range fields {
		if err := initializers.DB.Create(&field).Error; err != nil {
			log.Fatalf("❌ failed to seed maid form field '%s': %v", field.FieldKey, err)
		}
	}
}
