definitions:
  auth.SigninRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.Patient:
    description: Patient entity with ID, first name, and email
    properties:
      created_at:
        type: string
      email:
        example: john@example.com
        type: string
      first_name:
        example: John
        type: string
      id:
        example: 1
        type: integer
      updated_at:
        type: string
    type: object
  models.User:
    description: User entity with ID, first name, last name, email, password, date
      of birth, avatar, and blurhash
    properties:
      avatar:
        example: /images/avatar.png
        type: string
      blurhash:
        example: LKO2?V%2Tw=w]~RBVZRi};RPxuwH
        type: string
      created_at:
        type: string
      date_of_birth:
        example: "1990-01-01"
        type: string
      email:
        example: john@example.com
        type: string
      first_name:
        example: John
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: Doe
        type: string
      updated_at:
        type: string
    type: object
  patient.PatientInput:
    properties:
      email:
        type: string
      first_name:
        type: string
    required:
    - email
    - first_name
    type: object
  utils.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/signin:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Signin request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SigninRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: User Signin
      tags:
      - Auth
  /api/auth/signup:
    post:
      consumes:
      - multipart/form-data
      description: Registers a new user
      parameters:
      - description: First Name
        in: formData
        name: first_name
        required: true
        type: string
      - description: Last Name
        in: formData
        name: last_name
        type: string
      - description: Email
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Date of Birth
        format: date
        in: formData
        name: date_of_birth
        type: string
      - description: Avatar Image
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: User Signup
      tags:
      - Auth
  /api/patients/{id}:
    delete:
      description: Delete a patient by ID
      parameters:
      - description: Patient ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Delete a patient
      tags:
      - patients
  /patients:
    post:
      consumes:
      - application/json
      description: Create a new patient with first name and email
      parameters:
      - description: Patient data
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/patient.PatientInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Patient'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create a new patient
      tags:
      - patients
  /patients/{id}:
    get:
      description: Get a single patient using their ID
      parameters:
      - description: Patient ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Patient'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get a patient by ID
      tags:
      - patients
    put:
      consumes:
      - application/json
      description: Update patient information by ID
      parameters:
      - description: Patient ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated patient data
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/patient.PatientInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Patient'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Update a patient
      tags:
      - patients
swagger: "2.0"
