package constants

const (
	TypeStringField            = "string_field"
	TypeSingleRelation         = "single_relation"
	TypeSingleSelect           = "single_select"
	TypeRadioSelect            = "radio_select"
	TypeIntegerField           = "integer_field"
	TypeRichField              = "rich_field"
	TypeMultiRelation          = "multi_relation"
	TypeMultiSelect            = "multi_select"
	TypeFloatField             = "float_field"
	TypeCurrencyField          = "currency_field"
	TypeArrayField             = "array_field"
	TypeDateField              = "date_field"
	TypeDatetimeField          = "datetime_field"
	TypeImageField             = "image_field"
	TypeVideoField             = "video_field"
	TypeFileField              = "file_field"
	TypeCreatableSingleSelect  = "creatable_single_select"
	TypeUrl                    = "url_field"
	TypeSocialUrlField         = "social_url_field"
	TypePhoneField             = "phone_field"
	TypeEmailField             = "email_field"
	TypeRatingField            = "rating_field"
	TypePasswordField          = "password_field"
	TypeCreatableMultiRelation = "creatable_multi_select"
	TypeFormulaField           = "formula_field"
	TypeBoolField              = "boolean_field"
	TypeAttachmentsField       = "attachments_field"
	TypeLinkField              = "link_field"
)
